algoritmo "Calculo do Ex.2"
// Diciplina : Lógica de programação
// Autor : EduFM
// Data : 07/04/2026
var
// variaveis <3
     media, nota1, nota2, nota3, aluno: real

inicio
// Codiguinhos :3
   escreval("Calcule a média da nota de um aluno")
   escreva("Primeira nota: ")
   leia (nota1)
   
   escreva("Segunda nota: ")
   leia (nota2)
   
   escreva("Terceira nota: ")
   leia (nota3)

//calculozinho ^w^
               media <- nota1 + nota2 + nota3
               aluno <- media / 3
       escreval(" _______________________________________________________________________________")
//dados
       escreval("A média da nota deste aluno é ", aluno)

fimalgoritmo
