algoritmo "Calculo do Ex.3"
// Diciplina : Lógica de programação
// Autor : EduFM
// Data : 07/04/2026
var
// Variaveis <3
   area, altura, menor, maior, areaT: real

inicio
// Codiguinhos :3
   escreval ("Calcule a area de qualquer trapézio")
   escreva ("Qual a base maior? ")
   leia (maior)
   
   escreva ("Qual a base menor? ")
   leia (menor)
   
   escreva ("E a altura? ")
   leia (altura)

// Calculozinho ^w^
                area <- menor + maior
                areaT <- area * altura / 2

      escreval(" _______________________________________________________________________________")

// dados
   escreval("A area do trapézio é: ", areaT)

fimalgoritmo
