algoritmo "Calculo Ex.5"
// Diciplina : Lógica de programação
// Autor : EduFM
// Data : 13/04/2026
var
// Váriaveis <3
   c, f, valor, fracao: real

inicio
// Codiguinhos :3
   escreval ("conversor de °C para °F")
   escreva ("Informe a temperatura em °C:")
   leia (c)
   
//calculozinho ^w^
               valor <- c * 9
               fracao <- valor / 5
               f <- fracao + 32

   escreval(" _______________________________________________________________________________")
//dados
       escreval ("Sua temperatura convertida é: ",f,"°F")

fimalgoritmo
